# Generated by Django 3.1.3 on 2021-01-23 12:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=125)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Incorrect Format.Please use: '+999999999' Max 15 Chars.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(blank=True, max_length=200)),
                ('fiscal_number', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('TODO', 'To do'), ('ONGOING', 'On going'), ('REVIEW', 'In review'), ('FINISHED', 'Finished'), ('PAYED', 'Payed')], default='TODO', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('TODO', 'To do'), ('ONGOING', 'On going'), ('DONE', 'Done')], default='TODO', max_length=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
            ],
        ),
    ]
