# Generated by Django 3.2 on 2023-05-22 19:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('I', 'Individual'), ('C', 'Company')], default='I', max_length=1)),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(max_length=125)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Incorrect Format.Please use: '+999999999' Max 15 Chars.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(blank=True, max_length=200)),
                ('fiscal_number', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'CRM Configuration',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('TODO', 'To do'), ('ONGOING', 'On going'), ('REVIEW', 'In review'), ('FINISHED', 'Finished'), ('PAYED', 'Payed')], default='TODO', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('TODO', 'To do'), ('ONGOING', 'On going'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], default='TODO', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
            ],
        ),
    ]
