# Generated by Django 3.2 on 2021-04-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'CRM Configuration'},
        ),
        migrations.RemoveField(
            model_name='config',
            name='logo',
        ),
    ]
